'use client';
import { useEffect, useRef, useState } from 'react';
const questions=[{text:'what are you building?',placeholder:'Company, product, or project',replies:['AI product','Crypto app','Website']},{text:'nice. what kind of help do you need?',placeholder:'Product design, landing page, audit...',replies:['Product design','Landing page','UX audit']},{text:'what timeline are you thinking?',placeholder:'ASAP, Q3, flexible...',replies:['ASAP','Q3','Flexible']}];
export function InquiryChat(){
 const [step,setStep]=useState(-1);const [messages,setMessages]=useState<{role:string;text:string}[]>([]);const [input,setInput]=useState('');
 const flow=useRef<HTMLDivElement>(null);
 useEffect(()=>{flow.current?.scrollTo({top:flow.current.scrollHeight,behavior:'smooth'});},[messages]);
 function start(){setStep(0);setMessages([{role:'bot',text:questions[0].text}]);}
 function answer(value:string){if(!value.trim())return;const next=step+1;setMessages(v=>[...v,{role:'user',text:value},{role:'bot',text:next<3?questions[next].text:'this was a demo, have a beautiful day ♡'}]);setStep(next);setInput('');}
 return <section className="infinity-chat-demo chat-panel" aria-label="Demo inquiry chat"><div className="chat-scroll" ref={flow}><div className={`chat-flow ${step===-1?'chat-flow-welcome':''}`}>{(step===-1?['hi, i’m juliette’s inquiry bot','this is a component demonstration, so nothing sends anywhere','answer a few quick questions'].map(text=>({role:'bot',text})):messages).map((m,i)=><div className={`chat-row chat-row-${m.role}`} key={i}><div className={`chat-bubble chat-bubble-${m.role}`}>{m.text}</div></div>)}</div></div><div className="chat-compose">{step===-1?<div className="chat-compose-center"><button type="button" className="cta-button" onClick={start}>Start</button><p className="chat-privacy-note">Demo only. No Telegram, no API call.</p></div>:step===3?<div className="chat-compose-center"><button type="button" className="cta-button" onClick={()=>{setStep(-1);setMessages([]);}}>Restart</button></div>:<><div className="chat-chips" aria-label="Quick replies">{questions[step].replies.map(text=><button type="button" className="chat-chip" onClick={()=>answer(text)} key={text}>{text}</button>)}</div><form className="chat-form" onSubmit={e=>{e.preventDefault();answer(input);}}><input className="chat-input" aria-label="Demo answer" placeholder={questions[step].placeholder} value={input} onChange={e=>setInput(e.target.value)}/><button type="submit" className="chat-send" aria-label="Send demo answer" disabled={!input.trim()}>↑</button></form></>}</div></section>;
}
const steps=[['Connect your wallet','Link your Ethereum or Solana wallet.'],['Verify your identity','Quick KYC for on-chain compliance.'],['Deposit funds into vault','Transfer USDC, ETH, or SOL to your vault.'],['Set up transaction alerts','Get notified on swaps and liquidations.']];
export function Onboarding(){const[done,setDone]=useState<number[]>([]);function toggle(i:number){setDone(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i]);}return <div className="ix-card onboarding"><div className="onboarding-head"><span className="ix-title">Getting started</span><span className={`onboarding-progress ${done.length===4?'is-complete':''}`}>{done.length*25}%</span></div><p className="ix-sub onboarding-sub">{done.length===4?"All steps complete — you're ready to go.":'Set up your vault and start earning yield.'}</p><div className="onboarding-list">{steps.map(([title,description],i)=><button key={title} type="button" className={`onboarding-item ${done.includes(i)?'is-done':''}`} aria-pressed={done.includes(i)} onClick={()=>toggle(i)}><span className="onboarding-checkline"><span className={`onboarding-checkbox ${done.includes(i)?'is-checked':''}`}><svg viewBox="0 0 12 12" fill="none" aria-hidden="true"><path d="M2.5 6L5 8.5L9.5 3.5" stroke="#fff" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg></span>{i<3&&<span className="onboarding-connector"/>}</span><span className="onboarding-copy"><span className="onboarding-item-title">{title}</span><span className="onboarding-item-desc">{description}</span></span></button>)}</div><div className="onboarding-footer"><button className="ix-btn is-secondary" disabled={!done.length} onClick={()=>toggle(done[done.length-1])}>Back</button><button className="ix-btn is-primary" disabled={done.length===4} onClick={()=>toggle(steps.findIndex((_,i)=>!done.includes(i)))}>{done.length===4?'Done':'Next'}</button></div></div>;}
export function ProgressiveInput(){
 const[phase,setPhase]=useState(0);const[typed,setTyped]=useState('');const[count,setCount]=useState(3);const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{let active=false;let cancelled=false;let timer:ReturnType<typeof setTimeout>;let cycle=0;const tick=()=>{if(cancelled)return;if(active&&!matchMedia('(prefers-reduced-motion: reduce)').matches){cycle=(cycle+1)%32;setPhase(cycle<9?0:cycle<15?1:cycle<21?2:3);setTyped('3,482'.slice(0,Math.max(0,cycle-2)));setCount(Math.max(0,3-Math.floor((cycle-21)/2)));}timer=setTimeout(tick,500);};const observer=new IntersectionObserver(entries=>{active=entries[0].isIntersecting;});if(root.current)observer.observe(root.current);tick();return()=>{cancelled=true;clearTimeout(timer);observer.disconnect();};},[]);
 return <div className="input-stack" aria-label="Send crypto walkthrough demo" ref={root}><div className={`input-stack-flow ${phase===3?'is-hidden':''}`}>{Array.from({length:Math.min(phase,3)},(_,i)=><span className="input-stack-layer" key={i} style={{transform:`translateY(${-10*(phase-i)}px) scale(${1-.04*(phase-i)})`,zIndex:i}}/>)}<div className="input-stack-card" style={{zIndex:phase+1}}><div className="input-stack-step"><span className="input-stack-label">{['Amount','Wallet address','Network'][Math.min(phase,2)]}</span><span className="input-stack-input"><span className={phase===0&&!typed?'input-stack-placeholder':'input-stack-value'}>{phase===0?typed||'0.00':phase===1?'7xKXtg…gAsU':'Solana'}</span>{phase===0&&<><span className="input-stack-caret"/><span className="input-stack-suffix">USDC</span></>}</span></div></div></div><div className={`input-stack-confirm ${phase===3?'is-visible':''}`} aria-hidden={phase!==3}><span className="input-stack-confirm-title">Confirm transaction</span><div className="input-stack-confirm-rows">{[['Token','USDC'],['Amount','3,482'],['To','7xKXtg…gAsU'],['Network','Solana']].map(([label,value])=><div className="input-stack-confirm-row" key={label}><span>{label}</span><span className="input-stack-confirm-value">{value}</span></div>)}</div><div className="input-stack-confirm-actions"><span className="ix-btn is-secondary">Cancel</span><span className={`ix-btn is-primary input-stack-send ${count?'is-waiting':''}`}>Send{count>0?` (${count}s)`:''}</span></div></div></div>;
}
